### ISSUE TITLE
Wallet provider return something when massa station is not detected

### ISSUE THREAD

**Issue by altai0** [massalabs/wallet-provider#122]
Issue: When Massa Station is closed, there is no return back, so state updates cannot be provided. This can be supported for more dynamic websites.

**Comment by Ben-Rey** [comment]
This should solve this issue
https://github.com/massalabs/wallet-provider/blob/8bd24179f72f99f5aa27960bd040328ebd89a695/src/providersManager/ProvidersListener.ts
