### ISSUE TITLE
Max GAS Error with BearBy

### ISSUE THREAD

**Issue by altai0** [massalabs/wallet-provider#131]
<b>Identified problem</b>
> import { fromMAS } from "@massalabs/massa-web3";
> smart contract call gives max gas error when using coins: fromMAS(10)

<i>coins: BigInt(10000000000) does not cause any error </i>

The problem only applies to the BearBY wallet.

**Comment by qdrn** [comment]
Thanks for reporting @altai0 !

Do you mind sharing a minimal reproducible example ?

**Comment by altai0** [comment]
https://github.com/altai0/reproducible-test @qdrn

**Comment by Ben-Rey** [comment]
The problem was massa station and has been fixed here https://github.com/massalabs/wallet-provider/pull/186
