### ISSUE TITLE
Avoiding memory exhaustion

### ISSUE THREAD

**Issue by gregLibert** [massalabs/wallet-provider#16]
Add a counter per wallet provider to limit the allocation of entries in the map object in the function [here](https://github.com/massalabs/wallet-provider/blob/main/src/connector/Connector.ts#L138). When the limit is reached, throw an error linked to the wallet provider.

**Comment by BatiGencho** [comment]
@gregLibert Is this an OS depending limit (memory size tracking etc.) or a hardcoded number we deem to be ok ?

**Comment by Elli610** [comment]
@gregLibert should this issue be closed ?

**Comment by gregLibert** [comment]
> @gregLibert should this issue be closed ?

No, we will do it when we will have the bandwidth. Right now, it's not the priority
