### ISSUE TITLE
Needed Web3 functionalities for the wallet-provider

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/wallet-provider#2]
## Context

`Massa-web3` provides a whole set of wallet-related functionalities which are ready to use by the dapp developer. A whole list of the latter can be found [here](https://github.com/massalabs/massa-web3#wallet-operations) in the readme.
It would be nice to extend the current wallet-provider implementation to cover the same scope of interaction methods as provided by `massa-web3`, paving the way of being able to use the `massa-web3` library inside of `massa-wallet-provider`.

## User flow

N/A

## How to

The new features are to be added to the `account` and `provider` modules of the implementation alongside with their interfaces and linking in the `Connector` class, analogously to the already existing implementaitons.

## Technical details

The following methods are to be added:

-   `Generate New Account`
    ```ts
    await provider.generateNewAccount() :  Account
    ```
-   `Sending Native Token (pure MAS)`
    ```ts
    await account.sendTransaction(
        {
            fee: number,
            amount: string,
            recipientAddress: string
        }
    ): TxHash;
    ```
-   `Buying Rolls`
    ```ts
    await account.buyRolls(
        {
            fee: number,
            amount: number,
        }
    ): TxHash;
    ```
-   `Selling Rolls`
    ```ts
    await account.sellRolls(
        {
            fee: number,
            amount: number,
        }
    ): TxHash;
    ```

Above, TxHash is the operation Id which is of type `string`. Also, the `balance` method on the `account` is to be extended to return both the candidate and the final balances.

## QA testing

Testing is to be done in the conventional way established for testing the dapp - wallet provider described in the project [readme](https://github.com/massalabs/massa-wallet-provider)

**Comment by gregLibert** [comment]
ExecuteSC and CallSC functions are also missing to finish to cover the wallet scope.
