### ISSUE TITLE
Implement plugin wallet endpoints

### ISSUE THREAD

**Issue by gregLibert** [massalabs/wallet-provider#36]
new endpoints where emplemented here: https://github.com/massalabs/thyra-plugin-wallet/blob/main/api/walletApi-V0.yml

We should update our code to match those endpoints.

This Issue will be blocked until a new release of the plugin wallet (to be synch with @SlnPons for the release and with @Thykof for how to test the code using the main branche of tha repo)

**Comment by Thykof** [comment]
to play with the wallet API you can use the [postman collection](https://github.com/massalabs/thyra-plugin-wallet/blob/main/api/WalletPluginPostmanCollection.json). 

- follow the readme to install dependencies
- `go generate ./...`
- `STANDALONE=1 wails dev`
